export interface HelpSection {
  title: string;
  content: string;
}

export interface HelpFaq {
  question: string;
  answer: string;
}

export interface PageHelpContent {
  pageTitle: string;
  overview: string;
  howItWorks: HelpSection[];
  dataSources: HelpSection[];
  faqs: HelpFaq[];
}

export const helpContent: Record<string, PageHelpContent> = {
  "/dashboard": {
    pageTitle: "Command Center",
    overview:
      "The Command Center is the real-time operational hub for your entire portfolio. It aggregates KPIs across all connected portfolio companies, surfacing churn prevention impact, support deflection rates, operator hours saved, and agent ROI in a single view. This is where operating partners start their day to understand portfolio health at a glance.",
    howItWorks: [
      {
        title: "KPI Cards",
        content:
          "Four headline metrics are calculated from the latest daily KPI snapshots. Churn Prevented multiplies monthly snapshot values by 3 for a quarterly figure. Support Deflection shows the auto-resolution rate across all tickets. Hours Saved reflects monthly operator time displaced by agents. Agent ROI divides quarterly value created by quarterly agent costs. Click any card to drill into its calculation breakdown.",
      },
      {
        title: "90-Day Trend Chart",
        content:
          "A time-series chart pulls the last 90 days of KPI snapshots. NRR is rendered as an area fill and churn rate as a line overlay. When viewing 'All' orgs, values are averaged across portfolio companies. The chart refreshes every 60 seconds.",
      },
      {
        title: "Decision Summary & Agent Fleet",
        content:
          "The decision bar groups all pending decisions by severity (critical, high, medium, low) with total dollar exposure. Agent mini-cards show each deployed agent's status, run count, and value created. The activity feed streams the most recent audit log entries.",
      },
    ],
    dataSources: [
      {
        title: "SQLite \u2014 kpi_snapshots",
        content:
          "Daily KPI metrics per organization including NRR, churn rate, support deflection, operator hours, and agent costs. Queried via /api/dashboard/summary and /api/kpi endpoints.",
      },
      {
        title: "SQLite \u2014 agents, decisions, audit_log",
        content:
          "Agent fleet status, pending decision counts by severity, value at risk (sum of high/critical pending impact), and recent activity feed. All filtered by org_id.",
      },
      {
        title: "Polling: 30s summary, 60s trends",
        content:
          "React Query refetches the dashboard summary every 30 seconds and KPI trend data every 60 seconds to simulate near-real-time monitoring.",
      },
    ],
    faqs: [
      {
        question: "Is this data real or simulated?",
        answer:
          "This demo uses realistic synthetic data seeded into a SQLite database. In production, data flows from connected CRM, support, and billing systems via integrations. The data model and aggregation logic are production-grade.",
      },
      {
        question: "How is churn prevention actually measured?",
        answer:
          "Agents flag at-risk accounts based on signals (usage decline, support escalations, contract timing). When an intervention succeeds (renewal confirmed), the account's ARR is attributed as churn prevented. The methodology tracks flagged \u2192 intervened \u2192 retained.",
      },
      {
        question: "What does the Agent ROI number actually capture?",
        answer:
          "ROI = total value created (churn prevented + expansion identified) / total agent operating costs (compute, API calls, infrastructure) over the same quarter. It excludes implementation costs and focuses on marginal operating return.",
      },
      {
        question: "Can we see individual portfolio company performance?",
        answer:
          "Yes. Use the organization selector in the top bar to switch between portfolio companies or view aggregate ('All'). Every metric, chart, and feed filters to the selected org.",
      },
      {
        question: "How often does data refresh?",
        answer:
          "In this demo, the dashboard polls every 30 seconds for summary data and every 60 seconds for trend data. In production, refresh intervals are configurable per deployment and can be as low as real-time via webhooks.",
      },
    ],
  },

  "/decisions": {
    pageTitle: "Decision Inbox",
    overview:
      "The Decision Inbox is the Human-in-the-Loop (HITL) control plane. Every recommendation generated by agents surfaces here for human review before execution. This ensures that high-stakes actions \u2014 like contacting at-risk customers or approving expansion offers \u2014 always have a human in the loop with full context.",
    howItWorks: [
      {
        title: "HITL Tier System",
        content:
          "Decisions are classified into four tiers. Tier 1 (auto-execute): low-risk, high-confidence actions proceed automatically. Tier 2 (async review): medium-risk items await a single reviewer. Tier 3 (real-time approval): high-impact items require immediate review. Tier 4 (multi-person): fund-level decisions require two or more approvers.",
      },
      {
        title: "Confidence & Evidence",
        content:
          "Each decision includes a confidence score (0\u2013100%). Scores below 60% display in red, 60\u201380% in yellow, and above 80% in green. The evidence panel shows the source data that informed the recommendation \u2014 CRM records, support tickets, billing events \u2014 so reviewers can verify the agent's reasoning.",
      },
      {
        title: "Approve / Reject Flow",
        content:
          "Approving a decision updates its status, records the approver and timestamp, and creates a SHA-256 hash-chained audit log entry. Rejections follow the same audit trail. Every action is immutable and cryptographically linked to the previous entry.",
      },
    ],
    dataSources: [
      {
        title: "SQLite \u2014 decisions",
        content:
          "Core table storing all agent recommendations with type, severity, status, confidence score, impact dollars, evidence JSON, and recommended action. Supports filtering by severity, status, and agent_id with pagination.",
      },
      {
        title: "SQLite \u2014 agents (joined)",
        content:
          "Agent metadata joined to each decision to display which agent generated the recommendation and its accuracy rate.",
      },
      {
        title: "API: /api/decisions",
        content:
          "Paginated endpoint with query parameters for org_id, severity, status, agent_id, limit, and offset. Approve/reject actions hit /api/decisions/{id}/approve or /reject.",
      },
    ],
    faqs: [
      {
        question: "What happens if an agent recommendation is wrong?",
        answer:
          "Rejecting a decision feeds back into the agent's learning loop. The rejection is recorded in the audit trail. Over time, rejection patterns help refine agent confidence thresholds and reduce false positives. No action is taken on rejected decisions.",
      },
      {
        question: "Can we customize which decisions require approval?",
        answer:
          "Yes. The Policies page lets you define rules per decision type \u2014 which severity levels auto-approve, which require human review, and which need multi-person sign-off. Thresholds can be set per portfolio company.",
      },
      {
        question: "How does the confidence score get calculated?",
        answer:
          "Confidence is a composite score based on signal strength (how clear the data pattern is), data recency (how fresh the underlying signals are), and historical accuracy (how often similar recommendations were correct). The exact weighting is configurable per agent type.",
      },
      {
        question: "Is every decision auditable for compliance?",
        answer:
          "Yes. Every decision \u2014 creation, approval, rejection, escalation \u2014 is logged in the audit trail with a SHA-256 hash chain. Each entry links cryptographically to the previous one, making tampering detectable. This satisfies SOC 2 and LP reporting requirements.",
      },
      {
        question: "What's the typical approval turnaround time?",
        answer:
          "In production deployments, Tier 2 items average 4\u20138 hours for async review. Tier 3 items average under 30 minutes. The Work Queues page tracks SLA compliance across all pending decisions.",
      },
    ],
  },

  "/deals": {
    pageTitle: "Deal Room",
    overview:
      "The Deal Room provides a pipeline view of active and prospective portfolio investments. It tracks deals from initial sourcing through due diligence, IC review, and close \u2014 with AI-assisted thesis scoring and diligence tracking. This gives deal teams a structured view of pipeline velocity and stage composition.",
    howItWorks: [
      {
        title: "Kanban Pipeline",
        content:
          "Deals are organized in a 6-stage pipeline: Sourcing \u2192 Screening \u2192 Due Diligence \u2192 IC Review \u2192 Term Sheet \u2192 Closed. Each card shows the company name, sector, deal size, and current thesis score. Drag-and-drop is visual only in this demo.",
      },
      {
        title: "Pipeline Summary",
        content:
          "Aggregate metrics at the top show total pipeline value, deal count per stage, average deal size, and pipeline velocity (average days in current stage). These update as you filter by organization.",
      },
      {
        title: "Deal Detail Drawer",
        content:
          "Clicking a deal card opens a right-side drawer with full deal context: company overview, financial summary, thesis scoring breakdown, diligence checklist status, stage transition history, and key contacts.",
      },
    ],
    dataSources: [
      {
        title: "Static Mock Data",
        content:
          "Deal pipeline data is currently hardcoded with 10 representative portfolio companies across various stages. In production, this would connect to a deal management system (e.g., DealCloud, Affinity, or a custom CRM).",
      },
      {
        title: "API: /api/deals",
        content:
          "Returns the full deal list with computed pipeline summary metrics (total value, count by stage, average size). Filtered by org_id context.",
      },
    ],
    faqs: [
      {
        question: "How does AI-assisted thesis scoring work?",
        answer:
          "The thesis score evaluates deals across multiple dimensions: market size, competitive position, growth trajectory, management quality, and operational improvement potential. Each factor is weighted and scored based on available data. The score helps prioritize pipeline reviews but doesn't replace IC judgment.",
      },
      {
        question: "Does this integrate with our existing deal management tools?",
        answer:
          "In production, the Deal Room integrates via API with common deal management platforms (DealCloud, Affinity, Salesforce). The integration pulls deal metadata, stage transitions, and contact information in real-time.",
      },
      {
        question: "Can agents automatically surface deal insights?",
        answer:
          "Yes. The pipeline agent monitors deal progression and flags anomalies \u2014 stalled deals, thesis score changes based on new market data, or diligence findings that affect valuation. These surface in the Decision Inbox for human review.",
      },
      {
        question: "How is deal data kept confidential?",
        answer:
          "All deal data is org-isolated with strict access controls. Multi-tenant data separation ensures no cross-fund data leakage. The audit log tracks every access event for compliance.",
      },
    ],
  },

  "/queues": {
    pageTitle: "Work Queues",
    overview:
      "Work Queues organize pending agent recommendations into operational lanes \u2014 Revenue, Support, and Renewal \u2014 so the right team sees the right work. Each queue prioritizes items by impact score and tracks SLA compliance to ensure nothing falls through the cracks.",
    howItWorks: [
      {
        title: "Queue Lanes",
        content:
          "Decisions are automatically routed to queues based on the originating agent type. Revenue Cadence agent items go to the Revenue queue, Support Deflection items to the Support queue, and NRR agent items to the Renewal queue. Each lane is sorted by severity and impact dollars.",
      },
      {
        title: "Stats Bar",
        content:
          "The top stats bar shows total pending items, average time in queue (hours), items processed today, and SLA compliance percentage. These are calculated from the decisions table in real-time.",
      },
      {
        title: "Priority & Routing",
        content:
          "Items are color-coded by severity. Critical items appear at the top with a red indicator. Each item shows the account name, ARR at risk, agent confidence, and time since creation. Clicking routes to the Decision Inbox for full review.",
      },
    ],
    dataSources: [
      {
        title: "SQLite \u2014 decisions + agents",
        content:
          "Pending decisions are grouped by agent type (revenue_cadence, support_deflection, nrr) to form queue lanes. Joined with agent metadata for routing context.",
      },
      {
        title: "API: /api/queues",
        content:
          "Returns queue stats (total, avgTimeHours, processedToday, slaCompliance) and a Record of queue lanes, each containing an array of queue items with severity, impact, confidence, and account context.",
      },
    ],
    faqs: [
      {
        question: "How are SLA targets defined?",
        answer:
          "SLA targets are configurable per queue and severity level. Default targets: critical items within 4 hours, high within 24 hours, medium within 72 hours. These can be customized per portfolio company via the Policies page.",
      },
      {
        question: "Can we assign queue items to specific team members?",
        answer:
          "In production, queue items support assignment to individual operators or teams. The current demo shows the prioritized queue without assignment. Role-based routing (e.g., VP Sales sees Revenue queue, Support Lead sees Support queue) is configurable.",
      },
      {
        question: "What happens if an SLA is breached?",
        answer:
          "SLA breaches trigger escalation rules defined in Policies. This can include notification to a manager, automatic escalation to Tier 3 review, or flagging in the Command Center's decision summary. All escalations are audit-logged.",
      },
      {
        question: "How does impact scoring work?",
        answer:
          "Impact dollars represent the estimated revenue at risk or opportunity value. For renewal risks, it's the account's ARR. For expansion opportunities, it's the estimated incremental revenue. Agents calculate this from CRM and billing data.",
      },
    ],
  },

  "/portfolio": {
    pageTitle: "Portfolio Pulse",
    overview:
      "Portfolio Pulse provides a health monitoring dashboard across all portfolio companies. Each company is scored as Green (healthy), Yellow (watch), or Red (intervention needed) based on KPI thresholds calibrated to their stage. Anomaly alerts surface sudden changes that require attention.",
    howItWorks: [
      {
        title: "Health Scoring",
        content:
          "Company health status is computed from stage-aware KPI thresholds. A Series B company has different NRR, churn, and growth targets than a Seed-stage company. Each metric is evaluated against its stage-appropriate threshold, and the worst-performing metric determines the overall status (Red/Yellow/Green).",
      },
      {
        title: "Company Cards",
        content:
          "Each card shows the company name, stage, ARR, NRR, churn rate, and overall health status. Cards are sorted with Red companies first, then Yellow, then Green. Clicking a card opens a detail drawer with full metric breakdown and trend context.",
      },
      {
        title: "Anomaly Alerts",
        content:
          "The alerts section surfaces sudden metric changes \u2014 a churn spike, NRR drop, or support volume surge \u2014 that may not yet be reflected in the health status. These are early warning signals for operating partners to investigate.",
      },
    ],
    dataSources: [
      {
        title: "Static Mock Data",
        content:
          "Portfolio company profiles and health metrics are provided as structured mock data representing 5 companies at various stages (Seed+, Series A, Series B). In production, this pulls from the KPI snapshot history and CRM data.",
      },
      {
        title: "API: /api/portfolio",
        content:
          "Returns a summary (total companies, status counts, total ARR, avg NRR, value at risk), company array with health status and metrics, and anomaly alerts array.",
      },
    ],
    faqs: [
      {
        question: "How are health thresholds calibrated?",
        answer:
          "Thresholds are stage-aware. A Series B company with 95% NRR is Yellow, while a Seed company with 95% NRR is Green. Thresholds are based on industry benchmarks for each stage and can be customized per fund strategy.",
      },
      {
        question: "How quickly do anomalies get detected?",
        answer:
          "Anomaly detection runs on each data sync cycle. With typical integration refresh intervals of 15\u201360 minutes, most anomalies surface within an hour of the underlying data change. Critical threshold breaches trigger immediate alerts.",
      },
      {
        question: "Can we customize what metrics drive the health score?",
        answer:
          "Yes. The health scoring model is configurable. You can adjust which metrics are included, their relative weights, and the threshold values for each stage. Some funds add custom metrics like logo retention or expansion rate.",
      },
      {
        question: "How does this relate to board reporting?",
        answer:
          "Portfolio Pulse data feeds directly into board pack generation. The health status, trend data, and anomaly context can be exported as structured summaries for LP reporting and board presentations.",
      },
    ],
  },

  "/analytics": {
    pageTitle: "Analytics",
    overview:
      "The Analytics dashboard provides deep-dive reporting across all operational metrics. It surfaces revenue impact attribution, support efficiency gains, operator hours saved, and per-agent efficiency \u2014 giving operating partners the data they need to quantify the platform's value to the fund.",
    howItWorks: [
      {
        title: "Big Number Cards",
        content:
          "Four headline metrics: total revenue impact (churn prevented + expansion), support cost savings, operator hours recovered, and total agent runs. Each card shows the aggregate value with a contextual subtitle.",
      },
      {
        title: "Visualization Charts",
        content:
          "Revenue Impact chart shows decision outcomes by status (approved, rejected, pending). Support Metrics chart visualizes deflection rates and cost per ticket trends. Operator Hours chart tracks time saved across categories (triage, research, reporting, communications).",
      },
      {
        title: "Agent Efficiency Table",
        content:
          "A detailed table ranks each agent by total runs, decisions generated, value created, and accuracy rate. This helps identify which agents deliver the highest ROI and which may need tuning.",
      },
    ],
    dataSources: [
      {
        title: "SQLite \u2014 Multiple Aggregations",
        content:
          "The analytics endpoint performs cross-table aggregations: decisions grouped by status and severity, agent performance metrics, run statistics (count, duration, cost, tokens), and KPI trends over time.",
      },
      {
        title: "API: /api/analytics",
        content:
          "A single comprehensive endpoint returning decisions (byStatus, bySeverity, valueAtRisk), agents array, runs summary (total, completed, failed, avg_duration, total_cost), and kpiTrend time series.",
      },
    ],
    faqs: [
      {
        question: "How is revenue impact attributed to agents?",
        answer:
          "Revenue impact tracks the dollar value of approved decisions. When an agent flags a renewal risk and the account is saved, the ARR is attributed to that agent. Expansion revenue identified and confirmed is similarly attributed. This is conservative \u2014 only confirmed outcomes count.",
      },
      {
        question: "Can we benchmark across portfolio companies?",
        answer:
          "Yes. Switch to 'All' in the org selector to see aggregate metrics, or toggle between individual companies to compare. The analytics data normalizes by company size for fair comparison across different ARR scales.",
      },
      {
        question: "How do we report these numbers to LPs?",
        answer:
          "Analytics data is structured for LP reporting. Revenue impact, cost savings, and operational efficiency gains map directly to value creation narratives. The data can be exported and incorporated into quarterly fund reports.",
      },
      {
        question: "What drives the accuracy rate metric?",
        answer:
          "Accuracy rate = approved decisions / total decisions reviewed. An agent with 85% accuracy means 85% of its recommendations were deemed correct by human reviewers. Over time, this metric trends upward as agents learn from feedback.",
      },
    ],
  },

  "/agents": {
    pageTitle: "Agents",
    overview:
      "The Agents page is your AI fleet management console. It shows every deployed agent across the portfolio, their operational status, performance metrics, and cost. From here, operators can monitor fleet health, deploy new agents, and drill into individual agent performance.",
    howItWorks: [
      {
        title: "Fleet Health Banner",
        content:
          "The top banner summarizes fleet status: active agents, total runs, aggregate value created, and average accuracy. It provides an at-a-glance health check across all deployed agents for the selected organization.",
      },
      {
        title: "Agent Cards",
        content:
          "Each agent is displayed as a card showing name, type (Revenue Cadence, Support Deflection, NRR, Pipeline), status (active/paused/deploying), model used, and key metrics. Cards are color-coded by agent type.",
      },
      {
        title: "Performance Table & Deploy",
        content:
          "Below the cards, a sortable table provides detailed per-agent metrics: runs, decisions, value created, accuracy rate, and estimated cost. The Deploy button opens a dialog to configure and launch new agents.",
      },
    ],
    dataSources: [
      {
        title: "SQLite \u2014 agents + runs",
        content:
          "Agent metadata (name, type, status, model, config) and aggregated run data (total cost from runs table). The agents table stores cumulative metrics: total_runs, total_decisions, total_value_created, accuracy_rate.",
      },
      {
        title: "Polling: 30s refresh",
        content:
          "React Query refetches agent data every 30 seconds to reflect status changes from background agent runs. This ensures the fleet view stays current.",
      },
      {
        title: "API: /api/agents",
        content:
          "GET returns all agents for the org with joined cost data from runs. Individual agent detail available at /api/agents/{id} with full run history and decision breakdown.",
      },
    ],
    faqs: [
      {
        question: "What AI models do the agents use?",
        answer:
          "Agents are model-agnostic and can be configured to use different LLMs (GPT-4, Claude, Gemini) depending on the task requirements. The model is displayed on each agent card. Model selection balances capability, cost, and latency.",
      },
      {
        question: "How much do agents cost to operate?",
        answer:
          "Agent costs are tracked per-run, including API tokens and compute time. The budget bar in the top navigation shows daily spend against a configurable daily limit. The Analytics page breaks down cost efficiency per agent.",
      },
      {
        question: "Can agents be paused or rolled back?",
        answer:
          "Yes. Any agent can be paused immediately from its detail page. Pausing stops all scheduled runs and new decision generation. Agent configurations are versioned, so rolling back to a previous configuration is straightforward.",
      },
      {
        question: "How do agents improve over time?",
        answer:
          "Agents learn from the feedback loop of human approvals and rejections in the Decision Inbox. Decision patterns, rejection reasons, and accuracy trends inform model fine-tuning and confidence threshold adjustments. The Evaluations page tracks this improvement.",
      },
      {
        question: "What happens if an agent goes down?",
        answer:
          "Agent health is continuously monitored. Failed runs are logged with error details and trigger alerts. The fleet banner shows any agents in error state. Automatic retry policies handle transient failures. Persistent failures escalate to the operator via the notification bell.",
      },
    ],
  },

  "/playbooks": {
    pageTitle: "Playbooks",
    overview:
      "The Playbook Library contains reusable, battle-tested agent templates that encode operational best practices. Each playbook defines a specific value creation strategy \u2014 from churn prevention to support optimization \u2014 with a structured deployment methodology and measurable ROI framework.",
    howItWorks: [
      {
        title: "Playbook Cards",
        content:
          "Each playbook is presented as a card with its name, description, target agent type, and expected ROI range. Cards include a quick-deploy button and a details link for the full methodology.",
      },
      {
        title: "Detail Modal",
        content:
          "The detail view opens a full-width modal with tabbed sections: How It Works (methodology), Deliverables, Configuration parameters, ROI projection model, Rollout phases (pilot \u2192 expand \u2192 scale), FAQ, and required Integrations.",
      },
      {
        title: "Deploy Flow",
        content:
          "Deploying a playbook walks through a configuration dialog where you select the target organization, customize parameters (thresholds, schedules), and confirm. This creates a new agent instance pre-configured with the playbook's methodology.",
      },
    ],
    dataSources: [
      {
        title: "Static Mock Data",
        content:
          "Four playbook templates are defined with complete metadata: methodology descriptions, ROI models, deployment phases, configuration options, and FAQ. In production, playbooks can be created, versioned, and shared across the fund.",
      },
      {
        title: "API: /api/playbooks",
        content:
          "Returns the full playbook catalog. Each playbook includes name, description, type, ROI projections, deployment phases, integrations required, and configurable parameters.",
      },
    ],
    faqs: [
      {
        question: "Can we create custom playbooks?",
        answer:
          "Yes. While the library ships with battle-tested templates, custom playbooks can be authored for fund-specific strategies. You define the data sources, decision logic, escalation rules, and success metrics. Custom playbooks go through the same evaluation framework before deployment.",
      },
      {
        question: "How are playbook ROI projections calculated?",
        answer:
          "ROI projections are based on benchmarks from prior deployments. For example, the churn prevention playbook projects 15\u201325% reduction in avoidable churn based on median outcomes across similar B2B SaaS companies. Projections are ranges, not guarantees.",
      },
      {
        question: "What's the typical time to value for a playbook?",
        answer:
          "Most playbooks follow a 3-phase rollout: Pilot (2\u20134 weeks on one company), Expand (4\u20138 weeks across 3\u20135 companies), Scale (full portfolio). Initial signal visibility typically appears within the first week of pilot.",
      },
      {
        question: "Are playbooks portable across portfolio companies?",
        answer:
          "Playbooks are designed to be portable. The methodology is consistent, but configuration parameters (thresholds, schedules, integration mappings) are customized per company during deployment. A playbook proven at one company can be rapidly deployed to others.",
      },
    ],
  },

  "/evaluations": {
    pageTitle: "Evaluations",
    overview:
      "The Evaluations page provides an objective assessment of agent performance through structured scorecards and before/after comparison. It answers the fundamental question: are agents actually improving outcomes? This data is critical for justifying continued investment and identifying areas for optimization.",
    howItWorks: [
      {
        title: "Evaluation Scorecards",
        content:
          "Each agent type has a scorecard showing key performance dimensions: accuracy, precision, recall, F1 score, and business impact. Scores are color-coded (green >80%, yellow 60\u201380%, red <60%) and compared against baseline benchmarks.",
      },
      {
        title: "Before/After Comparison",
        content:
          "Charts display metric values before agent deployment vs. current, visualizing the delta. Metrics include churn rate, support resolution time, deflection rate, and operator hours. This provides the clearest evidence of agent impact.",
      },
      {
        title: "Evaluation History",
        content:
          "A results table shows historical evaluation runs with timestamps, scores, and trend indicators. This tracks how agent performance evolves over time and validates that improvements are sustained.",
      },
    ],
    dataSources: [
      {
        title: "Static Mock Data (per-org)",
        content:
          "Evaluation scorecards and before/after metrics are org-specific mock data. Each organization has tailored evaluation results reflecting their agent deployment timeline and outcomes. In production, evaluations run on scheduled cadences against live data.",
      },
      {
        title: "API: /api/evaluations",
        content:
          "Returns scorecards (per-agent accuracy metrics), beforeAfter (metric comparison data for charts), and history (timestamped evaluation results table). Filtered by org_id.",
      },
    ],
    faqs: [
      {
        question: "How often are evaluations run?",
        answer:
          "In production, evaluations run on configurable cadences \u2014 typically weekly for operational metrics and monthly for business impact metrics. Ad-hoc evaluations can be triggered after significant agent configuration changes.",
      },
      {
        question: "What methodology backs the evaluation scores?",
        answer:
          "Evaluations use standard ML metrics (accuracy, precision, recall, F1) applied to agent decisions. Business impact is measured by comparing pre/post agent deployment KPIs with statistical significance testing to isolate agent contribution from organic trends.",
      },
      {
        question: "Can we compare agent performance across portfolio companies?",
        answer:
          "Yes. Evaluation data is available per-org and in aggregate. Cross-company comparison reveals which environments agents perform best in, informing deployment strategy for new portfolio additions.",
      },
      {
        question: "What happens if evaluation scores decline?",
        answer:
          "Score declines trigger an automated alert to the operating team. Common causes include data quality changes, business model shifts, or seasonal patterns. The Evaluations page provides the diagnostic data to identify root causes and guide agent retraining.",
      },
    ],
  },

  "/value-creation": {
    pageTitle: "Value Creation Hub",
    overview:
      "The Value Creation Hub is the strategic command center for active portfolio interventions. It tracks phased value creation plans per company \u2014 from initial assessment through intervention to scale \u2014 with milestone tracking, KPI impact measurement, and operating cadence management.",
    howItWorks: [
      {
        title: "Company Selector & Phases",
        content:
          "Select a portfolio company to view its value creation plan. Each plan has three phases: Assess (data collection, baseline), Intervene (deploy agents, run playbooks), and Scale (expand successful interventions). A visual timeline shows phase progression with gate conditions.",
      },
      {
        title: "KPI Impact Tracker",
        content:
          "For each company, a KPI tracker shows baseline vs. current vs. target for key metrics. Status indicators (on-track, at-risk, behind) help identify which interventions are working and which need adjustment.",
      },
      {
        title: "Active Interventions & Cadence",
        content:
          "Active interventions list the specific actions underway (e.g., 'Deploy churn prevention agent', 'Optimize support routing'). The operating cadence section shows the scheduled touchpoints: weekly operator reviews, monthly board updates, quarterly strategic reviews.",
      },
    ],
    dataSources: [
      {
        title: "Static Mock Data",
        content:
          "Three portfolio companies have fully modeled value creation plans with phases, milestones, KPI targets, active interventions, and operating cadence schedules. In production, this connects to the fund's portfolio management and OKR tracking systems.",
      },
      {
        title: "API: /api/value-creation",
        content:
          "Returns company-specific value creation plans including phases (with milestones and gate conditions), KPI metrics (baseline/current/target), interventions, and cadence details. Filtered by company_id.",
      },
    ],
    faqs: [
      {
        question: "How are value creation targets set?",
        answer:
          "Targets are established during the Assess phase based on industry benchmarks, historical performance, and fund thesis. For example, a target of reducing churn from 8% to 5% is set based on peer company performance at similar scale and maturity.",
      },
      {
        question: "Who owns the value creation plan?",
        answer:
          "Value creation plans have shared ownership between the operating partner (strategic direction, resource allocation) and the portfolio company CEO/CRO (execution, team alignment). Milestone owners are assigned at the individual action level.",
      },
      {
        question: "How does this connect to the agents?",
        answer:
          "Value creation interventions often translate into agent deployments. For example, a 'Reduce churn' intervention deploys the NRR agent with a churn prevention playbook. Agent performance data flows back into the KPI tracker to measure impact.",
      },
      {
        question: "Can we track multiple simultaneous interventions?",
        answer:
          "Yes. Each company can have multiple active interventions across different operational areas. The hub tracks them independently with separate KPI targets and milestones, while the aggregate view shows total value creation progress.",
      },
    ],
  },

  "/simulator": {
    pageTitle: "Comp Simulator",
    overview:
      "The Comp Simulator is a sales compensation planning tool that helps operating partners design and validate comp plans for portfolio companies. It applies industry best practices \u2014 the 5x rule, 50/50 base/variable split, and accelerator design \u2014 to ensure plans drive the right sales behaviors while maintaining company economics.",
    howItWorks: [
      {
        title: "Plan Builder",
        content:
          "Input fields for base salary, OTE, annual quota, and accelerator multiplier. As you adjust values, the best practices bar immediately validates against three rules: the 5x Rule (quota should be 4\u20136x OTE), the 50/50 Split (base should be 45\u201355% of OTE), and the Accelerator Range (1.5\u20132.0x for overperformance).",
      },
      {
        title: "Scenario Output",
        content:
          "The scenario panel calculates at-quota earnings, overperformance scenarios (110%, 120%, 150% of quota), and the break-even point. It shows both the rep's total comp and the company's effective cost of sales at each level.",
      },
      {
        title: "Quota Economics Card",
        content:
          "Displays the underlying unit economics: quota-to-OTE ratio, variable component per dollar of quota, cost of sales as a percentage of quota, and the payback period for the comp plan investment.",
      },
    ],
    dataSources: [
      {
        title: "Client-Side Calculations",
        content:
          "All compensation modeling runs entirely in the browser. There are no API calls or database queries \u2014 the simulator uses pure mathematical formulas applied to the input parameters. This means sensitive comp data never leaves the client.",
      },
    ],
    faqs: [
      {
        question: "Why the 5x rule?",
        answer:
          "The 5x rule (quota = 5x OTE) is an industry standard that balances rep motivation with company economics. Below 4x, reps hit quota too easily and the company overpays. Above 6x, quotas feel unattainable and top performers leave. The sweet spot is 4\u20136x for most B2B SaaS.",
      },
      {
        question: "How should accelerators be structured?",
        answer:
          "Accelerators between 1.5\u20132.0x on attainment above quota are standard. Below 1.5x provides insufficient motivation to overperform. Above 2.0x can create unsustainable cost spikes. Some plans add a second accelerator tier above 150% attainment.",
      },
      {
        question: "Can we model different scenarios side by side?",
        answer:
          "The current simulator shows one plan at a time with multiple attainment scenarios. In production, a comparison mode allows side-by-side evaluation of different plan structures to find the optimal design.",
      },
      {
        question: "Does this account for multi-year quota ramping?",
        answer:
          "The current view models a single-year plan. For new hires, apply a ramp factor (typically 50% quota in Q1, 75% in Q2, 100% from Q3). The scenario output helps you understand the fully ramped economics.",
      },
      {
        question: "Is comp data stored or shared?",
        answer:
          "No. All calculations happen client-side in the browser. No compensation data is sent to any server, stored in any database, or logged in any audit trail. This ensures sensitive comp planning remains completely private.",
      },
    ],
  },

  "/audit": {
    pageTitle: "Audit Log",
    overview:
      "The Audit Log is the compliance backbone of the platform. Every action \u2014 agent runs, decision approvals, policy changes, data access \u2014 is recorded with a SHA-256 hash chain that cryptographically links each entry to the previous one. This creates a tamper-evident, immutable record that satisfies SOC 2, LP reporting, and regulatory requirements.",
    howItWorks: [
      {
        title: "Hash Chain Integrity",
        content:
          "Each audit entry contains a SHA-256 hash computed from the previous entry's hash plus the current entry's data. This chain means any modification to a historical entry would break the hash sequence, making tampering detectable. The banner at the top verifies chain integrity in real-time.",
      },
      {
        title: "Timeline View",
        content:
          "Entries are displayed in reverse chronological order with actor, action type, resource, and timestamp. Action type filters let you narrow to specific event categories (decision.created, decision.approved, agent.run_completed, etc.).",
      },
      {
        title: "Entry Detail Drawer",
        content:
          "Clicking an entry opens a drawer showing the full audit record: actor identity, action performed, affected resource, timestamp, previous hash, current hash, and the raw details JSON. The hash values are displayed for verification.",
      },
    ],
    dataSources: [
      {
        title: "SQLite \u2014 audit_log",
        content:
          "Core audit table with columns: id, org_id, prev_hash, hash, actor, action, resource_type, resource_id, details (JSON), created_at. Indexed by org_id for efficient filtering. Hash computed via SHA-256 in the application layer.",
      },
      {
        title: "API: /api/audit",
        content:
          "Paginated endpoint returning audit entries with total count, limit, and offset. Supports filtering by org_id. Each entry includes the full hash chain data for verification.",
      },
    ],
    faqs: [
      {
        question: "How does the hash chain work technically?",
        answer:
          "Each entry's hash = SHA-256(previous_entry_hash + action_type + resource_id + timestamp). The first entry uses a genesis hash. To verify integrity, you recompute the chain from the beginning \u2014 any discrepancy indicates tampering. This is the same principle behind blockchain integrity.",
      },
      {
        question: "Does this satisfy SOC 2 requirements?",
        answer:
          "Yes. The audit log provides the core evidence for SOC 2 Type II controls around access logging, change tracking, and data integrity. The hash chain adds cryptographic non-repudiation beyond typical audit logging. Entries are immutable \u2014 no delete or update operations exist.",
      },
      {
        question: "Can audit logs be exported for LP reporting?",
        answer:
          "Yes. The export button generates a CSV or JSON file of filtered audit entries. This can be incorporated into quarterly LP reports to demonstrate operational governance and AI oversight practices.",
      },
      {
        question: "How long are audit logs retained?",
        answer:
          "In production, audit log retention is configurable per fund requirements. Default is 7 years for financial compliance. Logs can be archived to cold storage after the active retention period while maintaining hash chain integrity.",
      },
      {
        question: "Who is the 'actor' in audit entries?",
        answer:
          "Actors include named agents (e.g., 'Revenue Cadence Agent'), human operators (by username), and system processes (e.g., 'system' for automated policy enforcement). This full attribution chain ensures every action is traceable to its source.",
      },
    ],
  },

  "/policies": {
    pageTitle: "Policies",
    overview:
      "The Policies page defines the governance rules that control how agents operate and when human intervention is required. Policies include approval requirements, auto-approve thresholds, two-person rules for high-stakes decisions, and budget limits \u2014 ensuring AI actions stay within defined guardrails.",
    howItWorks: [
      {
        title: "Policy Types",
        content:
          "Four policy types: Approval Required (which decision types need human sign-off), Auto-Approve (conditions under which low-risk decisions proceed automatically), Two-Person Rule (high-impact actions requiring dual approval), and Budget Limit (daily/monthly spend caps for agent operations).",
      },
      {
        title: "Enable/Disable Toggle",
        content:
          "Each policy has an enable/disable toggle for quick activation changes. Policies can be scoped to specific organizations or applied fund-wide. Rule parameters (thresholds, severity levels, dollar amounts) are configurable per policy.",
      },
      {
        title: "Rule Configuration",
        content:
          "Each policy's rules are stored as structured JSON specifying the conditions. For example, an auto-approve policy might specify: confidence > 85%, impact < $10,000, severity = low. Rules are evaluated in real-time as agents generate decisions.",
      },
    ],
    dataSources: [
      {
        title: "SQLite \u2014 policies",
        content:
          "Policies table with columns: id, org_id, name, type (approval_required, auto_approve, two_person, budget_limit), scope, rules (JSON), enabled (boolean), created_at. Rules JSON contains the specific conditions and thresholds.",
      },
      {
        title: "API: /api/policies",
        content:
          "Returns all policies for the selected org. Each policy includes its type, scope, enabled status, and the rules JSON. Toggle operations update the enabled flag.",
      },
    ],
    faqs: [
      {
        question: "What's the default policy configuration?",
        answer:
          "Out of the box: all critical and high-severity decisions require human approval, medium-severity decisions with confidence >85% auto-approve, two-person rule applies to decisions with impact >$100K, and daily budget is capped at $500. All defaults are customizable.",
      },
      {
        question: "Can policies differ across portfolio companies?",
        answer:
          "Yes. Policies are scoped per organization. A mature portfolio company with proven agent performance might have more permissive auto-approve rules, while a new deployment starts with stricter human oversight. Policies can also be applied fund-wide.",
      },
      {
        question: "How do policies interact with the HITL tier system?",
        answer:
          "Policies define the HITL tiers. The auto-approve policy sets Tier 1 boundaries, approval-required defines Tier 2/3, and two-person rule defines Tier 4. When an agent generates a decision, the policy engine evaluates all active policies to determine the correct tier.",
      },
      {
        question: "Are policy changes audited?",
        answer:
          "Yes. Every policy creation, modification, enable, or disable action is recorded in the Audit Log with the actor's identity, the previous and new configuration, and a timestamp. This ensures governance changes are fully traceable.",
      },
    ],
  },

  "/integrations": {
    pageTitle: "Integrations",
    overview:
      "The Integrations page shows all connected data sources that feed the platform. Agents rely on data from CRM, support, billing, communication, and data warehouse systems. This page monitors connection status, sync health, and last sync times to ensure the data pipeline powering agent decisions stays reliable.",
    howItWorks: [
      {
        title: "Connected Integrations",
        content:
          "Each connected system is displayed as a card showing the integration name, type (CRM, Support, Data Warehouse, etc.), connection status (connected/disconnected/error), health score (0\u2013100%), and last successful sync timestamp.",
      },
      {
        title: "Health Monitoring",
        content:
          "The status banner aggregates integration health across all connections. Health scores reflect sync success rate, data freshness, and error frequency. A degraded integration triggers alerts since agent decision quality depends on data quality.",
      },
      {
        title: "Available Integrations",
        content:
          "Below the connected systems, available integrations show systems that can be connected. The Add Integration flow guides through authentication, scope configuration, and initial sync. New integrations begin contributing data within minutes of connection.",
      },
    ],
    dataSources: [
      {
        title: "SQLite \u2014 integrations",
        content:
          "Integrations table with columns: id, org_id, name, type (crm, support, data_warehouse, communication, project_mgmt, reporting), status, config (JSON), last_sync_at, health_score. Indexed by org_id.",
      },
      {
        title: "Polling: 30s refresh",
        content:
          "React Query refetches integration status every 30 seconds to surface connection issues quickly. Stale sync timestamps are highlighted to indicate potential data freshness problems.",
      },
      {
        title: "API: /api/integrations",
        content:
          "Returns all integrations for the selected org with current status, health scores, and sync timestamps. Used to render both connected and available integration lists.",
      },
    ],
    faqs: [
      {
        question: "What systems does the platform integrate with?",
        answer:
          "Out of the box: Salesforce, HubSpot (CRM), Zendesk, Intercom (Support), Snowflake, BigQuery (Data Warehouse), Slack (Communication), Jira (Project Management), and Looker (Reporting). Custom integrations can be built via the API.",
      },
      {
        question: "How is integration data secured?",
        answer:
          "All integration credentials are encrypted at rest using AES-256. Data in transit uses TLS 1.3. OAuth 2.0 is used for authentication where supported. Credentials are never stored in plaintext and are accessible only to the integration engine, not to agents directly.",
      },
      {
        question: "What happens if an integration goes down?",
        answer:
          "Agents continue operating on the last known good data. The integration health score drops, triggering an alert. Agents' confidence scores automatically decrease for decisions that rely on stale data, ensuring reviewers are aware of reduced data freshness.",
      },
      {
        question: "How often does data sync?",
        answer:
          "Default sync intervals vary by integration type: CRM syncs every 15 minutes, support systems every 5 minutes, data warehouses every hour. Intervals are configurable per integration. Critical changes can trigger immediate webhooks.",
      },
      {
        question: "Can we control what data agents access?",
        answer:
          "Yes. Integration scopes define exactly which data objects and fields agents can access. For example, a CRM integration might expose opportunity data but not personal contact information. Scopes are configured during integration setup and enforced at the API level.",
      },
    ],
  },
};
