import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    scorecards: [
      {
        id: "eval-1",
        agent: "Revenue Cadence Agent",
        evalName: "Q4 2025 Replay",
        dataset: "Q4 2025 pipeline data (847 deals)",
        runDate: "Jan 15, 2026",
        accuracy: 91.2,
        precision: 91.8,
        recall: 97.2,
        truePositives: 423,
        falsePositives: 38,
        missed: 12,
        valueCaptured: 2100000,
        valueMissed: 312000,
        totalOpportunity: 2400000,
        status: "passed",
        statusLabel: "Passed",
        type: "revenue",
      },
      {
        id: "eval-2",
        agent: "Support Deflection Agent",
        evalName: "Last 90 Days Replay",
        dataset: "90-day ticket archive (3,241 tickets)",
        runDate: "Jan 22, 2026",
        accuracy: 87.4,
        precision: 96.6,
        recall: 82.1,
        truePositives: 1892,
        falsePositives: 67,
        missed: 412,
        valueCaptured: 48200,
        valueMissed: 0,
        totalOpportunity: 48200,
        status: "passed",
        statusLabel: "Passed",
        type: "support",
        csatImpact: "+0.2",
      },
      {
        id: "eval-3",
        agent: "NRR Agent",
        evalName: "Churn Prediction Backtest",
        dataset: "12-month renewal cohort (156 accounts)",
        runDate: "Jan 28, 2026",
        accuracy: 84.6,
        precision: 77.8,
        recall: 90.3,
        truePositives: 28,
        falsePositives: 8,
        missed: 3,
        valueCaptured: 890000,
        valueMissed: 142000,
        totalOpportunity: 1032000,
        status: "review",
        statusLabel: "Passed — review 3 missed",
        type: "nrr",
      },
    ],
    beforeAfter: [
      { metric: "Pipeline Coverage", before: 62, after: 84, unit: "%" },
      { metric: "Stage Conversion", before: 18, after: 26, unit: "%" },
      { metric: "Cycle Time", before: 45, after: 32, unit: "days", lowerBetter: true },
      { metric: "Deflection Rate", before: 12, after: 42, unit: "%" },
      { metric: "Avg Handle Time", before: 14, after: 8, unit: "min", lowerBetter: true },
      { metric: "Churn Rate", before: 8.2, after: 5.1, unit: "%", lowerBetter: true },
    ],
    history: [
      { agent: "Revenue Cadence", dataset: "Q4 2025 Pipeline", date: "Jan 15, 2026", accuracy: 91.2, status: "passed", duration: "4m 23s" },
      { agent: "Support Deflection", dataset: "90-Day Tickets", date: "Jan 22, 2026", accuracy: 87.4, status: "passed", duration: "12m 08s" },
      { agent: "NRR Agent", dataset: "12-Mo Renewals", date: "Jan 28, 2026", accuracy: 84.6, status: "review", duration: "8m 45s" },
      { agent: "Revenue Cadence", dataset: "Q3 2025 Pipeline", date: "Dec 10, 2025", accuracy: 88.7, status: "passed", duration: "4m 11s" },
      { agent: "Support Deflection", dataset: "60-Day Tickets", date: "Dec 18, 2025", accuracy: 83.1, status: "failed", duration: "9m 22s" },
      { agent: "NRR Agent", dataset: "6-Mo Renewals", date: "Nov 30, 2025", accuracy: 79.2, status: "review", duration: "6m 17s" },
    ],
  });
}
